apiVersion: apps/v1
kind: Deployment
metadata:
  name: project3-deployment
spec:
  replicas: 
  selector:
    matchLabels:
      app: project3
  template:
    metadata:
      labels:
        app: project3
        
    spec:
      containers:
      - name: project3
        image: quay.io/ran_ju_vincie/cs401_project3_0
        ports:
        - containerPort: 5105
        env:
        - name: REDIS_HOST
          value: "152.3.65.126"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_INPUT_KEY
          value: "metrics"
       
  
